cd /lib/systemd/system
# sudo systemctl mask avahi-daemon.socket
# sudo systemctl mask bluetooth.target
# sudo systemctl mask dev-hugepages.mount
# sudo systemctl mask dev-mqueue.mount
# sudo systemctl mask sys-kernel-config.mount
# sudo systemctl mask sys-kernel-debug.mount
# sudo systemctl mask abrtd.service
# sudo systemctl mask abrt-journal-core.service
# sudo systemctl mask abrt-oops.service
# sudo systemctl mask abrt-pstoreoops.service
# sudo systemctl mask abrt-vmcore.service
# sudo systemctl mask abrt-xorg.service
# sudo systemctl mask accounts-daemon.service
# sudo systemctl mask acpid.service
# sudo systemctl mask alsa-restore.service
# sudo systemctl mask alsa-state.service
# sudo systemctl mask anaconda-direct.service
# sudo systemctl mask anaconda-nm-config.service
# sudo systemctl mask anaconda-noshell.service
# sudo systemctl mask anaconda-pre.service
# sudo systemctl mask anaconda.service
# sudo systemctl mask anaconda-shell@.service
# sudo systemctl unmask anaconda-sshd.service
# sudo systemctl mask anaconda-tmux@.service
# sudo systemctl mask argus.service
# sudo systemctl mask arp-ethers.service
# sudo systemctl mask atd.service
# sudo systemctl mask atopacct.service
# sudo systemctl mask atopgpu.service
# sudo systemctl mask atop-rotate.service
# sudo systemctl mask atop.service
# sudo systemctl mask auditd.service
# sudo systemctl mask auth-rpcgss-module.service
# sudo systemctl mask autovt@.service
# sudo systemctl mask avahi-daemon.service
# sudo systemctl mask bitlbee.service
# sudo systemctl mask bitlbee@.service
# sudo systemctl mask blivet.service
# sudo systemctl mask blk-availability.service
# sudo systemctl mask bluetooth.service
# sudo systemctl mask brltty.service
# sudo systemctl mask btattach-bcm@.service
# sudo systemctl mask canberra-system-bootup.service
# sudo systemctl mask canberra-system-shutdown-reboot.service
# sudo systemctl mask canberra-system-shutdown.service
# sudo systemctl mask chrony-dnssrv@.service
# sudo systemctl mask chronyd.service
# sudo systemctl mask chrony-wait.service
# sudo systemctl mask ckb-next-daemon.service
# sudo systemctl mask clean-mount-point@.service
sudo systemctl mask colord.service
# sudo systemctl mask configure-printer@.service
# sudo systemctl mask console-getty.service
# sudo systemctl mask containerd.service
# sudo systemctl mask container-getty@.service
# sudo systemctl mask cpupower.service
# sudo systemctl mask crond.service
# sudo systemctl mask cups-browsed.service
# sudo systemctl mask cups.service
# sudo systemctl mask dbus-broker.service
# sudo systemctl mask dbus-daemon.service
# sudo systemctl mask dbus-org.freedesktop.home1.service
# sudo systemctl mask dbus-org.freedesktop.hostname1.service
# sudo systemctl mask dbus-org.freedesktop.import1.service
# sudo systemctl mask dbus-org.freedesktop.locale1.service
# sudo systemctl mask dbus-org.freedesktop.login1.service
# sudo systemctl mask dbus-org.freedesktop.machine1.service
# sudo systemctl mask dbus-org.freedesktop.portable1.service
# sudo systemctl mask dbus-org.freedesktop.timedate1.service
# sudo systemctl mask dbxtool.service
# sudo systemctl mask debug-shell.service
# sudo systemctl mask dkms.service
# sudo systemctl mask dm-event.service
# sudo systemctl mask dmraid-activation.service
# sudo systemctl mask dnf-automatic-download.service
# sudo systemctl mask dnf-automatic-install.service
# sudo systemctl mask dnf-automatic-notifyonly.service
# sudo systemctl mask dnf-automatic.service
# sudo systemctl mask dnfdaemon.service
# sudo systemctl mask dnf-makecache.service
# sudo systemctl mask dnf-system-upgrade-cleanup.service
# sudo systemctl mask dnf-system-upgrade.service
# sudo systemctl mask dnsmasq.service
sudo systemctl mask docker.service
# sudo systemctl mask dracut-cmdline.service
# sudo systemctl mask dracut-initqueue.service
# sudo systemctl mask dracut-mount.service
# sudo systemctl mask dracut-pre-mount.service
# sudo systemctl mask dracut-pre-pivot.service
# sudo systemctl mask dracut-pre-trigger.service
# sudo systemctl mask dracut-pre-udev.service
# sudo systemctl mask dracut-shutdown.service
# sudo systemctl mask drbd.service
# sudo systemctl mask emergency.service
# sudo systemctl mask etckeeper.service
# sudo systemctl mask fancontrol.service
# sudo systemctl mask fcoe.service
# sudo systemctl mask festival.service
# sudo systemctl mask firewalld.service
# sudo systemctl mask flatpak-add-fedora-repos.service
# sudo systemctl mask flatpak-system-helper.service
# sudo systemctl mask fprintd.service
# sudo systemctl mask fstrim.service
# sudo systemctl mask fwupd-offline-update.service
# sudo systemctl mask fwupd-refresh.service
# sudo systemctl mask fwupd.service
# sudo systemctl mask geoclue.service
# sudo systemctl mask getty@.service
# sudo systemctl mask grafana-server.service
# sudo systemctl mask grub-boot-indeterminate.service
# sudo systemctl mask gssproxy.service
# sudo systemctl mask hddtemp.service
# sudo systemctl mask htcacheclean.service
sudo systemctl mask httpd.service
sudo systemctl mask httpd@.service
sudo systemctl mask httpd.service.d
# sudo systemctl mask hypervfcopyd.service
# sudo systemctl mask hypervkvpd.service
# sudo systemctl mask hypervvssd.service
# sudo systemctl mask iio-sensor-proxy.service
# sudo systemctl mask import-state.service
# sudo systemctl mask initial-setup-reconfiguration.service
# sudo systemctl mask initial-setup.service
# sudo systemctl mask initrd-cleanup.service
# sudo systemctl mask initrd-parse-etc.service
# sudo systemctl mask initrd-switch-root.service
# sudo systemctl mask initrd-udevadm-cleanup-db.service
# sudo systemctl mask instperf.service
# sudo systemctl mask iodine-client.service
# sudo systemctl mask ipsec.service
# sudo systemctl mask irqbalance.service
# sudo systemctl mask iscsid.service
# sudo systemctl mask iscsi.service
# sudo systemctl mask iscsi-shutdown.service
# sudo systemctl mask iscsiuio.service
# sudo systemctl mask kdump.service
# sudo systemctl mask kmod-static-nodes.service
# sudo systemctl mask ldconfig.service
# sudo systemctl mask libvirtd.service
# sudo systemctl mask lldpad.service
# sudo systemctl mask lm_sensors.service
# sudo systemctl mask loadmodules.service
# sudo systemctl mask logrotate.service
# sudo systemctl mask low-memory-monitor.service
# sudo systemctl mask lvm2-lvmpolld.service
# sudo systemctl mask lvm2-monitor.service
# sudo systemctl mask lvm2-pvscan@.service
# sudo systemctl mask man-db-cache-update.service
# sudo systemctl mask man-db-restart-cache-update.service
# sudo systemctl mask mariadb@bootstrap.service.d
# sudo systemctl mask mariadb.service
# sudo systemctl mask mariadb@.service
# sudo systemctl mask mariadb.service.d
# sudo systemctl mask mcelog.service
# sudo systemctl mask mdadm-grow-continue@.service
# sudo systemctl mask mdadm-last-resort@.service
# sudo systemctl mask mdmonitor.service
# sudo systemctl mask mdmon@.service
# sudo systemctl mask mlocate-updatedb.service
# sudo systemctl mask ModemManager.service
# sudo systemctl mask modprobe@.service
# sudo systemctl mask monitorix.service
# sudo systemctl mask motion.service
# sudo systemctl mask multipathd.service
# sudo systemctl mask mysql-mmm-monitor.service
# sudo systemctl mask ndctl-monitor.service
# sudo systemctl mask NetworkManager-dispatcher.service
# sudo systemctl mask NetworkManager.service
# sudo systemctl mask NetworkManager-wait-online.service
# sudo systemctl mask nfs-blkmap.service
# sudo systemctl mask nfs-convert.service
# sudo systemctl mask nfsdcld.service
# sudo systemctl mask nfs-idmapd.service
# sudo systemctl mask nfs-mountd.service
# sudo systemctl mask nfs-server.service
# sudo systemctl mask nfs-utils.service
# sudo systemctl mask nftables.service
# sudo systemctl mask nis-domainname.service
# sudo systemctl mask numad.service
# sudo systemctl mask oddjobd.service
# sudo systemctl mask openfortivpn@.service
sudo systemctl mask openvpn-client@.service
sudo systemctl mask openvpn-server@.service
# sudo systemctl mask ostree-finalize-staged.service
# sudo systemctl mask ostree-prepare-root.service
# sudo systemctl mask ostree-remount.service
# sudo systemctl mask packagekit-offline-update.service
# sudo systemctl mask packagekit.service
# sudo systemctl mask polkit.service
# sudo systemctl mask powerline.service
sudo systemctl mask pppoe-server.service
# sudo systemctl mask psacct.service
# sudo systemctl mask qemu-guest-agent.service
# sudo systemctl mask qemu-pr-helper.service
# sudo systemctl mask quotaon.service
# sudo systemctl mask radvd.service
# sudo systemctl mask raid-check.service
# sudo systemctl mask rc-local.service
# sudo systemctl mask rdisc.service
# sudo systemctl mask rdma-load-modules@.service
# sudo systemctl mask rdma-ndd.service
# sudo systemctl mask rdma.service
# sudo systemctl mask realmd.service
# sudo systemctl mask rescue.service
# sudo systemctl mask rhsmcertd.service
# sudo systemctl mask rhsm-facts.service
# sudo systemctl mask rhsm.service
# sudo systemctl mask rngd.service
# sudo systemctl mask rpcbind.service
# sudo systemctl mask rpc-gssd.service
# sudo systemctl mask rpc-statd-notify.service
# sudo systemctl mask rpc-statd.service
# sudo systemctl mask rrdcached.service
# sudo systemctl mask rsyslog.service
# sudo systemctl mask rtirq.service
# sudo systemctl mask rtkit-daemon.service
# sudo systemctl mask saslauthd.service
# sudo systemctl mask sddm.service
# sudo systemctl mask selinux-autorelabel-mark.service
# sudo systemctl mask selinux-autorelabel.service
# sudo systemctl mask sensord.service
# sudo systemctl mask serial-getty@.service
# sudo systemctl mask smartd.service
# sudo systemctl mask snapd.autoimport.service
# sudo systemctl mask snapd.failure.service
# sudo systemctl mask snapd.seeded.service
# sudo systemctl mask snapd.service
# sudo systemctl mask speech-dispatcherd.service
# sudo systemctl mask spice-vdagentd.service
# sudo systemctl mask sshd-keygen@.service
# sudo systemctl mask sshd.service
# sudo systemctl mask sshd@.service
# sudo systemctl mask sssd-autofs.service
# sudo systemctl mask sssd-kcm.service
# sudo systemctl mask sssd-nss.service
# sudo systemctl mask sssd-pac.service
# sudo systemctl mask sssd-pam.service
# sudo systemctl mask sssd.service
# sudo systemctl mask sssd-ssh.service
# sudo systemctl mask sssd-sudo.service
# sudo systemctl mask strongswan.service
# sudo systemctl mask strongswan-starter.service
# sudo systemctl mask switcheroo-control.service
# sudo systemctl mask systemd-ask-password-console.service
# sudo systemctl mask systemd-ask-password-wall.service
# sudo systemctl mask systemd-backlight@.service
# sudo systemctl mask systemd-binfmt.service
# sudo systemctl mask systemd-bless-boot.service
# sudo systemctl mask systemd-boot-check-no-failures.service
# sudo systemctl mask systemd-boot-system-token.service
# sudo systemctl mask systemd-coredump@.service
# sudo systemctl mask systemd-exit.service
# sudo systemctl mask systemd-firstboot.service
# sudo systemctl mask systemd-fsck-root.service
# sudo systemctl mask systemd-fsck@.service
# sudo systemctl mask systemd-halt.service
# sudo systemctl mask systemd-hibernate-resume@.service
# sudo systemctl mask systemd-hibernate.service
# sudo systemctl mask systemd-homed.service
# sudo systemctl mask systemd-hostnamed.service
# sudo systemctl mask systemd-hostnamed.service.d
# sudo systemctl mask systemd-hwdb-update.service
# sudo systemctl mask systemd-hybrid-sleep.service
# sudo systemctl mask systemd-importd.service
# sudo systemctl mask systemd-initctl.service
sudo systemctl mask systemd-journal-catalog-update.service
sudo systemctl mask systemd-journald.service
sudo systemctl mask systemd-journald@.service
sudo systemctl mask systemd-journal-flush.service
# sudo systemctl mask systemd-kexec.service
# sudo systemctl mask systemd-localed.service
# sudo systemctl mask systemd-logind.service
# sudo systemctl mask systemd-machined.service
# sudo systemctl mask systemd-machine-id-commit.service
# sudo systemctl mask systemd-modules-load.service
# sudo systemctl mask systemd-networkd.service
# sudo systemctl mask systemd-networkd-wait-online.service
# sudo systemctl mask systemd-network-generator.service
# sudo systemctl mask systemd-nspawn@.service
# sudo systemctl mask systemd-portabled.service
# sudo systemctl mask systemd-poweroff.service
# sudo systemctl mask systemd-pstore.service
# sudo systemctl mask systemd-quotacheck.service
# sudo systemctl mask systemd-random-seed.service
# sudo systemctl mask systemd-reboot.service
# sudo systemctl mask systemd-remount-fs.service
# sudo systemctl mask systemd-repart.service
# sudo systemctl mask systemd-resolved.service
# sudo systemctl mask systemd-rfkill.service
# sudo systemctl mask systemd-suspend.service
# sudo systemctl mask systemd-suspend-then-hibernate.service
# sudo systemctl mask systemd-sysctl.service
# sudo systemctl mask systemd-sysusers.service
# sudo systemctl mask systemd-timedated.service
# sudo systemctl mask systemd-timesyncd.service
# sudo systemctl mask systemd-time-wait-sync.service
# sudo systemctl mask systemd-tmpfiles-clean.service
# sudo systemctl mask systemd-tmpfiles-setup-dev.service
# sudo systemctl mask systemd-tmpfiles-setup.service
# sudo systemctl mask systemd-udevd.service
# sudo systemctl mask systemd-udev-settle.service
# sudo systemctl mask systemd-udev-trigger.service
# sudo systemctl mask systemd-udev-trigger.service.d
# sudo systemctl mask systemd-update-done.service
# sudo systemctl mask systemd-update-utmp-runlevel.service
# sudo systemctl mask systemd-update-utmp.service
# sudo systemctl mask systemd-userdbd.service
# sudo systemctl mask systemd-user-sessions.service
# sudo systemctl mask systemd-vconsole-setup.service
# sudo systemctl mask systemd-volatile-root.service
# sudo systemctl mask system-update-cleanup.service
# sudo systemctl mask tcsd.service
# sudo systemctl mask teamd@.service
# sudo systemctl mask thermald.service
# sudo systemctl mask tor-master.service
sudo systemctl mask --now tor.service
sudo systemctl mask --now tor@.service
# sudo systemctl mask tuned.service
# sudo systemctl mask udisks2.service
# sudo systemctl mask unbound-anchor.service
# sudo systemctl mask upower.service
# sudo systemctl mask usb_modeswitch@.service
# sudo systemctl mask user-runtime-dir@.service
# sudo systemctl mask user@.service
# sudo systemctl mask vboxclient.service
# sudo systemctl mask vboxservice.service
# sudo systemctl mask vdr.service
# sudo systemctl mask vgauthd.service
# sudo systemctl mask virtlockd.service
# sudo systemctl mask virtlogd.service
# sudo systemctl mask virtnetworkd.service
# sudo systemctl mask virtproxyd.service
# sudo systemctl mask virtqemud.service
# sudo systemctl mask virtsecretd.service
# sudo systemctl mask virtstoraged.service
# sudo systemctl mask vmtoolsd.service
# sudo systemctl mask wacom-inputattach@.service
# sudo systemctl mask wpa_supplicant.service
# sudo systemctl mask xl2tpd.service
# sudo systemctl mask zram.service
# sudo systemctl mask zram-swap.service
# sudo systemctl mask zvbid.service
systemctl daemon-reload
sudo grub2-mkconfig -o /boot/efi/EFI/fedora/grub.cfg
sudo dracut -f
