cd /lib/systemd/system
sudo systemctl unmask avahi-daemon.socket
sudo systemctl unmask bluetooth.target
sudo systemctl unmask dev-hugepages.mount
sudo systemctl unmask dev-mqueue.mount
sudo systemctl unmask sys-kernel-config.mount
sudo systemctl unmask sys-kernel-debug.mount
sudo systemctl unmask abrtd.service
sudo systemctl unmask abrt-journal-core.service
sudo systemctl unmask abrt-oops.service
sudo systemctl unmask abrt-pstoreoops.service
sudo systemctl unmask abrt-vmcore.service
sudo systemctl unmask abrt-xorg.service
sudo systemctl unmask accounts-daemon.service
sudo systemctl unmask acpid.service
sudo systemctl unmask alsa-restore.service
sudo systemctl unmask alsa-state.service
sudo systemctl unmask anaconda-direct.service
sudo systemctl unmask anaconda-nm-config.service
sudo systemctl unmask anaconda-noshell.service
sudo systemctl unmask anaconda-pre.service
sudo systemctl unmask anaconda.service
sudo systemctl unmask anaconda-shell@.service
sudo systemctl unmask anaconda-sshd.service
sudo systemctl unmask anaconda-tmux@.service
sudo systemctl unmask argus.service
sudo systemctl unmask arp-ethers.service
sudo systemctl unmask atd.service
sudo systemctl unmask atopacct.service
sudo systemctl unmask atopgpu.service
sudo systemctl unmask atop-rotate.service
sudo systemctl unmask atop.service
sudo systemctl unmask auditd.service
sudo systemctl unmask auth-rpcgss-module.service
sudo systemctl unmask autovt@.service
sudo systemctl unmask avahi-daemon.service
sudo systemctl unmask bitlbee.service
sudo systemctl unmask bitlbee@.service
sudo systemctl unmask blivet.service
sudo systemctl unmask blk-availability.service
sudo systemctl unmask bluetooth.service
sudo systemctl unmask brltty.service
sudo systemctl unmask btattach-bcm@.service
sudo systemctl unmask canberra-system-bootup.service
sudo systemctl unmask canberra-system-shutdown-reboot.service
sudo systemctl unmask canberra-system-shutdown.service
sudo systemctl unmask chrony-dnssrv@.service
sudo systemctl unmask chronyd.service
sudo systemctl unmask chrony-wait.service
sudo systemctl unmask ckb-next-daemon.service
sudo systemctl unmask clean-mount-point@.service
sudo systemctl unmask colord.service
sudo systemctl unmask configure-printer@.service
sudo systemctl unmask console-getty.service
sudo systemctl unmask containerd.service
sudo systemctl unmask container-getty@.service
sudo systemctl unmask cpupower.service
sudo systemctl unmask crond.service
sudo systemctl unmask cups-browsed.service
sudo systemctl unmask cups.service
sudo systemctl unmask dbus-broker.service
sudo systemctl unmask dbus-daemon.service
sudo systemctl unmask dbus-org.freedesktop.home1.service
sudo systemctl unmask dbus-org.freedesktop.hostname1.service
sudo systemctl unmask dbus-org.freedesktop.import1.service
sudo systemctl unmask dbus-org.freedesktop.locale1.service
sudo systemctl unmask dbus-org.freedesktop.login1.service
sudo systemctl unmask dbus-org.freedesktop.machine1.service
sudo systemctl unmask dbus-org.freedesktop.portable1.service
sudo systemctl unmask dbus-org.freedesktop.timedate1.service
sudo systemctl unmask dbxtool.service
sudo systemctl unmask debug-shell.service
sudo systemctl unmask dkms.service
sudo systemctl unmask dm-event.service
sudo systemctl unmask dmraid-activation.service
sudo systemctl unmask dnf-automatic-download.service
sudo systemctl unmask dnf-automatic-install.service
sudo systemctl unmask dnf-automatic-notifyonly.service
sudo systemctl unmask dnf-automatic.service
sudo systemctl unmask dnfdaemon.service
sudo systemctl unmask dnf-makecache.service
sudo systemctl unmask dnf-system-upgrade-cleanup.service
sudo systemctl unmask dnf-system-upgrade.service
sudo systemctl unmask dnsmasq.service
sudo systemctl unmask docker.service
sudo systemctl unmask dracut-cmdline.service
sudo systemctl unmask dracut-initqueue.service
sudo systemctl unmask dracut-mount.service
sudo systemctl unmask dracut-pre-mount.service
sudo systemctl unmask dracut-pre-pivot.service
sudo systemctl unmask dracut-pre-trigger.service
sudo systemctl unmask dracut-pre-udev.service
sudo systemctl unmask dracut-shutdown.service
sudo systemctl unmask drbd.service
sudo systemctl unmask emergency.service
sudo systemctl unmask etckeeper.service
sudo systemctl unmask fancontrol.service
sudo systemctl unmask fcoe.service
sudo systemctl unmask festival.service
sudo systemctl unmask firewalld.service
sudo systemctl unmask flatpak-add-fedora-repos.service
sudo systemctl unmask flatpak-system-helper.service
sudo systemctl unmask fprintd.service
sudo systemctl unmask fstrim.service
sudo systemctl unmask fwupd-offline-update.service
sudo systemctl unmask fwupd-refresh.service
sudo systemctl unmask fwupd.service
sudo systemctl unmask geoclue.service
sudo systemctl unmask getty@.service
sudo systemctl unmask grafana-server.service
sudo systemctl unmask grub-boot-indeterminate.service
sudo systemctl unmask gssproxy.service
sudo systemctl unmask hddtemp.service
sudo systemctl unmask htcacheclean.service
sudo systemctl unmask httpd.service
sudo systemctl unmask httpd@.service
sudo systemctl unmask httpd.service.d
sudo systemctl unmask hypervfcopyd.service
sudo systemctl unmask hypervkvpd.service
sudo systemctl unmask hypervvssd.service
sudo systemctl unmask iio-sensor-proxy.service
sudo systemctl unmask import-state.service
sudo systemctl unmask initial-setup-reconfiguration.service
sudo systemctl unmask initial-setup.service
sudo systemctl unmask initrd-cleanup.service
sudo systemctl unmask initrd-parse-etc.service
sudo systemctl unmask initrd-switch-root.service
sudo systemctl unmask initrd-udevadm-cleanup-db.service
sudo systemctl unmask instperf.service
sudo systemctl unmask iodine-client.service
sudo systemctl unmask ipsec.service
sudo systemctl unmask irqbalance.service
sudo systemctl unmask iscsid.service
sudo systemctl unmask iscsi.service
sudo systemctl unmask iscsi-shutdown.service
sudo systemctl unmask iscsiuio.service
sudo systemctl unmask kdump.service
sudo systemctl unmask kmod-static-nodes.service
sudo systemctl unmask ldconfig.service
sudo systemctl unmask libvirtd.service
sudo systemctl unmask lldpad.service
sudo systemctl unmask lm_sensors.service
sudo systemctl unmask loadmodules.service
sudo systemctl unmask logrotate.service
sudo systemctl unmask low-memory-monitor.service
sudo systemctl unmask lvm2-lvmpolld.service
sudo systemctl unmask lvm2-monitor.service
sudo systemctl unmask lvm2-pvscan@.service
sudo systemctl unmask man-db-cache-update.service
sudo systemctl unmask man-db-restart-cache-update.service
sudo systemctl unmask mariadb@bootstrap.service.d
sudo systemctl unmask mariadb.service
sudo systemctl unmask mariadb@.service
sudo systemctl unmask mariadb.service.d
sudo systemctl unmask mcelog.service
sudo systemctl unmask mdadm-grow-continue@.service
sudo systemctl unmask mdadm-last-resort@.service
sudo systemctl unmask mdmonitor.service
sudo systemctl unmask mdmon@.service
sudo systemctl unmask mlocate-updatedb.service
sudo systemctl unmask ModemManager.service
sudo systemctl unmask modprobe@.service
sudo systemctl unmask monitorix.service
sudo systemctl unmask motion.service
sudo systemctl unmask multipathd.service
sudo systemctl unmask mysql-mmm-monitor.service
sudo systemctl unmask ndctl-monitor.service
sudo systemctl unmask NetworkManager-dispatcher.service
sudo systemctl unmask NetworkManager.service
sudo systemctl unmask NetworkManager-wait-online.service
sudo systemctl unmask nfs-blkmap.service
sudo systemctl unmask nfs-convert.service
sudo systemctl unmask nfsdcld.service
sudo systemctl unmask nfs-idmapd.service
sudo systemctl unmask nfs-mountd.service
sudo systemctl unmask nfs-server.service
sudo systemctl unmask nfs-utils.service
sudo systemctl unmask nftables.service
sudo systemctl unmask nis-domainname.service
sudo systemctl unmask numad.service
sudo systemctl unmask oddjobd.service
sudo systemctl unmask openfortivpn@.service
sudo systemctl unmask openvpn-client@.service
sudo systemctl unmask openvpn-server@.service
sudo systemctl unmask ostree-finalize-staged.service
sudo systemctl unmask ostree-prepare-root.service
sudo systemctl unmask ostree-remount.service
sudo systemctl unmask packagekit-offline-update.service
sudo systemctl unmask packagekit.service
sudo systemctl unmask polkit.service
sudo systemctl unmask powerline.service
sudo systemctl unmask pppoe-server.service
sudo systemctl unmask psacct.service
sudo systemctl unmask qemu-guest-agent.service
sudo systemctl unmask qemu-pr-helper.service
sudo systemctl unmask quotaon.service
sudo systemctl unmask radvd.service
sudo systemctl unmask raid-check.service
sudo systemctl unmask rc-local.service
sudo systemctl unmask rdisc.service
sudo systemctl unmask rdma-load-modules@.service
sudo systemctl unmask rdma-ndd.service
sudo systemctl unmask rdma.service
sudo systemctl unmask realmd.service
sudo systemctl unmask rescue.service
sudo systemctl unmask rhsmcertd.service
sudo systemctl unmask rhsm-facts.service
sudo systemctl unmask rhsm.service
sudo systemctl unmask rngd.service
sudo systemctl unmask rpcbind.service
sudo systemctl unmask rpc-gssd.service
sudo systemctl unmask rpc-statd-notify.service
sudo systemctl unmask rpc-statd.service
sudo systemctl unmask rrdcached.service
sudo systemctl unmask rsyslog.service
sudo systemctl unmask rtirq.service
sudo systemctl unmask rtkit-daemon.service
sudo systemctl unmask saslauthd.service
sudo systemctl unmask sddm.service
sudo systemctl unmask selinux-autorelabel-mark.service
sudo systemctl unmask selinux-autorelabel.service
sudo systemctl unmask sensord.service
sudo systemctl unmask serial-getty@.service
sudo systemctl unmask smartd.service
sudo systemctl unmask snapd.autoimport.service
sudo systemctl unmask snapd.failure.service
sudo systemctl unmask snapd.seeded.service
sudo systemctl unmask snapd.service
sudo systemctl unmask speech-dispatcherd.service
sudo systemctl unmask spice-vdagentd.service
sudo systemctl unmask sshd-keygen@.service
sudo systemctl unmask sshd.service
sudo systemctl unmask sshd@.service
sudo systemctl unmask sssd-autofs.service
sudo systemctl unmask sssd-kcm.service
sudo systemctl unmask sssd-nss.service
sudo systemctl unmask sssd-pac.service
sudo systemctl unmask sssd-pam.service
sudo systemctl unmask sssd.service
sudo systemctl unmask sssd-ssh.service
sudo systemctl unmask sssd-sudo.service
sudo systemctl unmask strongswan.service
sudo systemctl unmask strongswan-starter.service
sudo systemctl unmask switcheroo-control.service
sudo systemctl unmask systemd-ask-password-console.service
sudo systemctl unmask systemd-ask-password-wall.service
sudo systemctl unmask systemd-backlight@.service
sudo systemctl unmask systemd-binfmt.service
sudo systemctl unmask systemd-bless-boot.service
sudo systemctl unmask systemd-boot-check-no-failures.service
sudo systemctl unmask systemd-boot-system-token.service
sudo systemctl unmask systemd-coredump@.service
sudo systemctl unmask systemd-exit.service
sudo systemctl unmask systemd-firstboot.service
sudo systemctl unmask systemd-fsck-root.service
sudo systemctl unmask systemd-fsck@.service
sudo systemctl unmask systemd-halt.service
sudo systemctl unmask systemd-hibernate-resume@.service
sudo systemctl unmask systemd-hibernate.service
sudo systemctl unmask systemd-homed.service
sudo systemctl unmask systemd-hostnamed.service
sudo systemctl unmask systemd-hostnamed.service.d
sudo systemctl unmask systemd-hwdb-update.service
sudo systemctl unmask systemd-hybrid-sleep.service
sudo systemctl unmask systemd-importd.service
sudo systemctl unmask systemd-initctl.service
sudo systemctl unmask systemd-journal-catalog-update.service
sudo systemctl unmask systemd-journald.service
sudo systemctl unmask systemd-journald@.service
sudo systemctl unmask systemd-journal-flush.service
sudo systemctl unmask systemd-kexec.service
sudo systemctl unmask systemd-localed.service
sudo systemctl unmask systemd-logind.service
sudo systemctl unmask systemd-machined.service
sudo systemctl unmask systemd-machine-id-commit.service
sudo systemctl unmask systemd-modules-load.service
sudo systemctl unmask systemd-networkd.service
sudo systemctl unmask systemd-networkd-wait-online.service
sudo systemctl unmask systemd-network-generator.service
sudo systemctl unmask systemd-nspawn@.service
sudo systemctl unmask systemd-portabled.service
sudo systemctl unmask systemd-poweroff.service
sudo systemctl unmask systemd-pstore.service
sudo systemctl unmask systemd-quotacheck.service
sudo systemctl unmask systemd-random-seed.service
sudo systemctl unmask systemd-reboot.service
sudo systemctl unmask systemd-remount-fs.service
sudo systemctl unmask systemd-repart.service
sudo systemctl unmask systemd-resolved.service
sudo systemctl unmask systemd-rfkill.service
sudo systemctl unmask systemd-suspend.service
sudo systemctl unmask systemd-suspend-then-hibernate.service
sudo systemctl unmask systemd-sysctl.service
sudo systemctl unmask systemd-sysusers.service
sudo systemctl unmask systemd-timedated.service
sudo systemctl unmask systemd-timesyncd.service
sudo systemctl unmask systemd-time-wait-sync.service
sudo systemctl unmask systemd-tmpfiles-clean.service
sudo systemctl unmask systemd-tmpfiles-setup-dev.service
sudo systemctl unmask systemd-tmpfiles-setup.service
sudo systemctl unmask systemd-udevd.service
sudo systemctl unmask systemd-udev-settle.service
sudo systemctl unmask systemd-udev-trigger.service
sudo systemctl unmask systemd-udev-trigger.service.d
sudo systemctl unmask systemd-update-done.service
sudo systemctl unmask systemd-update-utmp-runlevel.service
sudo systemctl unmask systemd-update-utmp.service
sudo systemctl unmask systemd-userdbd.service
sudo systemctl unmask systemd-user-sessions.service
sudo systemctl unmask systemd-vconsole-setup.service
sudo systemctl unmask systemd-volatile-root.service
sudo systemctl unmask system-update-cleanup.service
sudo systemctl unmask tcsd.service
sudo systemctl unmask teamd@.service
sudo systemctl unmask thermald.service
sudo systemctl unmask tor-master.service
sudo systemctl unmask tor.service
sudo systemctl unmask tor@.service
sudo systemctl unmask tuned.service
sudo systemctl unmask udisks2.service
sudo systemctl unmask unbound-anchor.service
sudo systemctl unmask upower.service
sudo systemctl unmask usb_modeswitch@.service
sudo systemctl unmask user-runtime-dir@.service
sudo systemctl unmask user@.service
sudo systemctl unmask vboxclient.service
sudo systemctl unmask vboxservice.service
sudo systemctl unmask vdr.service
sudo systemctl unmask vgauthd.service
sudo systemctl unmask virtlockd.service
sudo systemctl unmask virtlogd.service
sudo systemctl unmask virtnetworkd.service
sudo systemctl unmask virtproxyd.service
sudo systemctl unmask virtqemud.service
sudo systemctl unmask virtsecretd.service
sudo systemctl unmask virtstoraged.service
sudo systemctl unmask vmtoolsd.service
sudo systemctl unmask wacom-inputattach@.service
sudo systemctl unmask wpa_supplicant.service
sudo systemctl unmask xl2tpd.service
sudo systemctl unmask zram.service
sudo systemctl unmask zram-swap.service
sudo systemctl unmask zvbid.service
systemctl daemon-reload
sudo grub2-mkconfig -o /boot/efi/EFI/fedora/grub.cfg
sudo dracut -f
